services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres_db
    ports:
      - "5433:5432"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    depends_on:
      - db
    env_file:
      - .env.production
    ports:
      - "4000:3000"
    volumes:
      - ./credentials:/app/credentials:ro
    platform: linux/amd64